fragment fragmentCharacters on Characters {
  info {
    count
    pages
    next
    prev
  }
  results {
    id
    name
    image
  }
}

query Characters {
  characters(
    page: 2
  filter: {
    name: "morty"
  }
) {
  ...fragmentCharacters
  }
}